version: "3"

services:
  api:
    build: api
    restart: always
    ports:
      - "1323:1323"

  alerter:
    build: alerter
    restart: always

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: donhaialert
      MYSQL_USER: mopeneko
      MYSQL_PASSWORD: mopepass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
