version: "3"

services:
  api:
    build: api

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: donhaialert
      MYSQL_USER: mopeneko
      MYSQL_PASSWORD: mopepass
